/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xj7V1uZNl8s
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Home from "@/app/pricing/metanote"
import Metafolip from "@/app/pricing/metafolip"

export function Othercomp() {
  return (
    <section className="w-full py-12">
      <div className="container grid max-w-3xl items-center gap-4 px-4 md:px-6 mx-auto">
        <div className="flex flex-col gap-1">
          <h2 className="text-blue-500 text-3xl font-bold">Other Apps</h2>
          <p className="text-gray-500 dark:text-gray-400">More amazing apps made by Shafi Cloud</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <CardHeader className="flex items-center gap-4">
              <ActivityIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Folip</CardTitle>
                <CardDescription>A productivity app for tracking your daily tasks and noting things</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="grid gap-4 grid-cols-2">
            <Metafolip/>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex items-center gap-4">
              <CalendarIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Sumaize</CardTitle>
                <CardDescription>A sleek article summarizer app for simplification</CardDescription>
              </div>
            </CardHeader>
            <CardContent>
              <center>
              <a href="https://sumaize.vercel.app">
                <Button size="sm">
                  Open On Web
                  </Button>
                  </a>
                  </center>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex items-center gap-4">
              <MailIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>NoteBro</CardTitle>
                <CardDescription>An note taking app designed for simplicity and efficiency</CardDescription>
              </div>
            </CardHeader>
            <CardContent>
              <Home/>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}


function ActivityIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
    </svg>
  )
}


function CalendarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  )
}


function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MusicIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 18V5l12-2v13" />
      <circle cx="6" cy="18" r="3" />
      <circle cx="18" cy="16" r="3" />
    </svg>
  )
}
